apiVersion: apps/v1
kind: Deployment
metadata:
  name: shetland-deployment
  labels:
    app: shetland
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shetland
  template:
    metadata:
      labels:
        app: shetland
    spec:
      containers:
      - name: shetland
        image: jokerofnoxus/shetland:v1.1
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
---

apiVersion: v1
kind: Service
metadata:
  name: shetland-service
spec:
  selector:
    app: shetland
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer
